#!/bin/bash
# Local end-to-end test of the CI review pipeline's model step.
#
# Replicates what .github/workflows/review.yml does around the Claude model
# step — trusted artifacts generated by the real engine, the workflow's own
# tool allowlist and sandbox settings (parsed from the workflow file, so this
# test cannot drift from CI), CI env vars — then runs YOUR WORKING COPY of the
# plugin against a seeded vulnerable diff and applies the publish step's
# validation checks to the report it stages.
#
# What this does NOT cover: the trusted workflow steps themselves (checkout,
# rollout policy, publish/approve) — those only run in Actions — and
# Linux-specific sandbox behavior (bubblewrap) when run on macOS.
#
# Usage: npm run test:e2e [-- --model <model>] [--max-turns <n>] [--keep]
# Cost: one real model run (default claude-sonnet-5), typically 5-15 minutes.
# Note: the skill contract uses fixed /tmp/agent_review_* and /tmp/review_*
# paths, so this clears and reuses those on your machine.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKFLOW="$ROOT/.github/workflows/review.yml"
MODEL="claude-sonnet-5"
MAX_TURNS=120
KEEP=""
while [ $# -gt 0 ]; do
  case "$1" in
    --model) MODEL="$2"; shift 2 ;;
    --max-turns) MAX_TURNS="$2"; shift 2 ;;
    --keep) KEEP=1; shift ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done

command -v claude >/dev/null || { echo "FAIL: claude CLI not found"; exit 1; }

# ── The CI contract, read from the workflow itself ───────────────────────────
ALLOWED_TOOLS=$(sed -n 's/.*--allowedTools "\([^"]*\)".*/\1/p' "$WORKFLOW" | head -1)
SETTINGS=$(sed -n "s/^ *settings: '\(.*\)'$/\1/p" "$WORKFLOW" | head -1)
[ -n "$ALLOWED_TOOLS" ] || { echo "FAIL: could not parse --allowedTools from review.yml"; exit 1; }
[ -n "$SETTINGS" ] || { echo "FAIL: could not parse settings from review.yml"; exit 1; }
echo "▶ CI allowlist: $ALLOWED_TOOLS"
echo "▶ CI sandbox settings: $SETTINGS"

echo "▶ Rebuilding dist/ from engine sources..."
(cd "$ROOT" && npm run --silent build)

# ── Scratch consumer repo with a seeded, findable vulnerability ──────────────
SCRATCH=$(mktemp -d -t agent-review-e2e)
CONSUMER="$SCRATCH/consumer"
TRUSTED="$SCRATCH/trusted/.claude/review"
mkdir -p "$CONSUMER/src"
cd "$CONSUMER"
git init -q -b master
mkdir -p .claude/review
cp -R "$ROOT/fixtures/wealthtracker/." .claude/review/
cat > src/auth.js <<'JS'
function login(user, password) {
  if (!user) return null;
  return db.query("SELECT * FROM users WHERE name = '" + user + "'");
}
module.exports = { login };
JS
git add -A && git -c user.email=e2e@test -c user.name=e2e commit -qm base
BASE=$(git rev-parse HEAD)
git checkout -qb feature
cat > src/auth.js <<'JS'
function login(user, password) {
  return db.query("SELECT * FROM users WHERE name = '" + user + "' AND pw = '" + password + "'");
}
module.exports = { login };
JS
git add -A && git -c user.email=e2e@test -c user.name=e2e commit -qm "feat: check password in login"
HEAD=$(git rev-parse HEAD)

# ── Trusted artifacts, exactly as review.yml's steps produce them ────────────
mkdir -p "$(dirname "$TRUSTED")"
cp -R "$CONSUMER/.claude" "$SCRATCH/trusted/"
git diff "$BASE..$HEAD" > /tmp/agent_review_full_diff.txt
echo '[]' > /tmp/agent_review_ast_grep.json
echo '{"check_runs":[]}' > /tmp/agent_review_checks.json
node "$ROOT/dist/agent-review.cjs" evidence --root "$CONSUMER" --review-dir "$TRUSTED" \
  --diff /tmp/agent_review_full_diff.txt --ast-grep /tmp/agent_review_ast_grep.json \
  --ci /tmp/agent_review_checks.json > /tmp/agent_review_evidence.json
echo '{"version":1,"repositories":[]}' > /tmp/agent_review_context.json
: > /tmp/agent_review_previous_comment.md
rm -f /tmp/agent_review_comment.md /tmp/agent_review_report.md /tmp/review_env.sh \
  /tmp/review_plan.json /tmp/agent_review_ledger.json /tmp/agent_review_status.json

# ── The model step ────────────────────────────────────────────────────────────
echo "▶ Running /agent-review:review auto ci with the local plugin ($MODEL, max $MAX_TURNS turns)..."
TRANSCRIPT="$SCRATCH/transcript.jsonl"
set +e
env AGENT_REVIEW_CI=1 AGENT_REVIEW_DEBATE=false \
  AGENT_REVIEW_PREVIOUS_COMMENT=/tmp/agent_review_previous_comment.md \
  AGENT_REVIEW_COMMENT_OUT=/tmp/agent_review_comment.md \
  AGENT_REVIEW_EVIDENCE=/tmp/agent_review_evidence.json \
  AGENT_REVIEW_CONTEXT_INVENTORY=/tmp/agent_review_context.json \
  AGENT_REVIEW_CONTEXT_DIR="$SCRATCH/context" \
  AGENT_REVIEW_DIR="$TRUSTED" \
  AGENT_REVIEW_ROLLOUT_MODE=shadow \
  PR_NUMBER=9999 BASE_REF="$BASE" HEAD_REF="$HEAD" \
  GITHUB_REPOSITORY=example/e2e-scratch CLAUDE_CODE_SUBPROCESS_ENV_SCRUB=1 \
  claude --plugin-dir "$ROOT" -p '/agent-review:review auto ci' \
    --allowedTools "$ALLOWED_TOOLS" --settings "$SETTINGS" \
    --model "$MODEL" --max-turns "$MAX_TURNS" \
    --output-format stream-json --verbose > "$TRANSCRIPT" 2>&1
CLAUDE_STATUS=$?
set -e
echo "▶ Model run finished (exit $CLAUDE_STATUS). Transcript: $TRANSCRIPT"

# ── The publish step's validation, verbatim ───────────────────────────────────
COMMENT=/tmp/agent_review_comment.md
FAIL() { echo "❌ FAIL: $1"; echo "   transcript: $TRANSCRIPT"; exit 1; }
[ -s "$COMMENT" ] || FAIL "Claude exited without producing an agent-review report"
BYTES=$(wc -c < "$COMMENT")
[ "$BYTES" -le 65500 ] || FAIL "report is $BYTES bytes; GitHub's comment limit is 65,536"
REPORT_HEAD=$(tr -d '\r' < "$COMMENT" \
  | sed -n 's/^<!-- agent-review-head: \([0-9a-f]\{7,40\}\) -->$/\1/p' | head -1)
[ "$REPORT_HEAD" = "$HEAD" ] || FAIL "report covers '${REPORT_HEAD:-no head}' but the PR head is $HEAD"
REPORT_ROLLOUT=$(tr -d '\r' < "$COMMENT" \
  | sed -n 's/^<!-- agent-review-rollout: \([a-z]*\) -->$/\1/p' | head -1)
[ "$REPORT_ROLLOUT" = "shadow" ] || FAIL "rollout marker is '${REPORT_ROLLOUT:-missing}', expected shadow"
node - "$COMMENT" /tmp/agent_review_evidence.json "$ROOT" <<'NODE' || FAIL "report state validation"
const fs = require('fs');
const path = require('path');
const comment = fs.readFileSync(process.argv[2], 'utf8').replace(/\r/g, '');
const evidence = JSON.parse(fs.readFileSync(process.argv[3], 'utf8'));
const match = comment.match(/^<!-- agent-review-ledger: (.*) -->$/m);
if (!match) throw new Error('report has no findings ledger');
const ledger = JSON.parse(match[1]);
const present = new Set(ledger.map((entry) => entry.signature));
const missing = (evidence.staticFindings || []).filter((finding) => !present.has(finding.signature));
if (missing.length) throw new Error(`report omitted ${missing.length} deterministic static finding(s)`);
// Stricter than the publish step: the address flow needs exactly one of each marker.
const A = require(path.join(process.argv[4], 'engine/addressState.cjs'));
const state = A.extractReportState(comment);
console.log(`   ledger: ${state.ledger.length} finding(s), openBlockers=${state.status.openBlockers}, pass=${state.status.pass}`);
NODE

echo "✅ PASS: the staged report survives every publish-step check ($BYTES bytes)"
echo "   report: $COMMENT"
if [ -n "$KEEP" ]; then
  echo "   scratch kept: $SCRATCH"
else
  rm -rf "$SCRATCH"
fi
